#cloud-config
package_update: true
package_upgrade: true
packages:
 - consul
write_files:
- owner: root:root
  path: /etc/consul/ssl/consul-agent-ca.pem
  permissions: '0644'
  content: |
    ${ca_cert_chain}
- owner: root:root
  path: /etc/consul/ssl/server-consul-1.pem
  permissions: '0644'
  content: |
    ${server_02_cert}
- owner: root:root
  path: /etc/consul/ssl/server-consul-1-key.pem
  permissions: '0644'
  content: |
    ${server_02_key}
- owner: root:root
  path: /etc/consul/ssl/client-consul-0.pem
  permissions: '0644'
  content: |
    ${client_cert}
- owner: root:root
  path: /etc/consul/ssl/client-consul-0-key.pem
  permissions: '0644'
  content: |
    ${client_key}
- owner: root:root
  path: /etc/consul.d/00-server.json
  permissions: '0644'
  content: |
    {
        "datacenter": "${datacenter}",
        "data_dir": "/var/lib/consul",
        "encrypt": "${cluster_encrypt_key}",
        "leave_on_terminate": true,
        "rejoin_after_leave": true,
        "bootstrap_expect": 3,
        "server": true,
        "addresses": {
          "https": "0.0.0.0",
          "dns" : "0.0.0.0"
        },
        "ports": {
          "http": -1,
          "https": 8501,
          "dns": 8600,
          "grpc": -1
        },
        "verify_incoming": false,
        "verify_outgoing": true,
        "verify_server_hostname": true,
        "ca_file": "/etc/consul/ssl/consul-agent-ca.pem",
        "cert_file": "/etc/consul/ssl/server-consul-1.pem",
        "key_file": "/etc/consul/ssl/server-consul-1-key.pem",
        "auto_encrypt": {
          "allow_tls": false
        },
        "disable_remote_exec": true,
        "enable_script_checks": true,
        "dns_config": {
            "enable_truncate": true,
            "only_passing": true
        },
        "enable_syslog": true,
        "ui": true,
        "start_join": [
          "${server_1_ip_address}"
        ]
    }
- owner: root:root
  path: /etc/consul.d/01-acls.json
  permissions: '0644'
  content: |
    {
      "acl": {
        "enabled": true,
        "default_policy": "deny",
        "enable_token_persistence": true,
        "tokens": {
          "master": "${cluster_master_token}"
        }
       }  
    }
- owner: root:root
  path: /etc/consul/default_policies/default-policy.hcl
  permissions: '0644'
  content: |
    node_prefix "" {
      policy = "read"
    }
    
    service_prefix "" {
      policy = "read"
    }
- owner: root:root
  path: /etc/consul/default_policies/node-service-write.hcl
  permissions: '0644'
  content: |
    node_prefix "" {
      policy = "write"
    }
    
    service_prefix "" {
      policy = "write"
    }
- owner: root:root
  path: /etc/consul/client.env
  permissions: '0644'
  content: |
    export CONSUL_CLIENT_CERT=/etc/consul/ssl/client-consul-0.pem
    export CONSUL_CLIENT_KEY=/etc/consul/ssl/client-consul-0-key.pem
    export CONSUL_CACERT=/etc/consul/ssl/consul-agent-ca.pem
    export CONSUL_HTTP_SSL=true
    export CONSUL_HTTP_ADDR=https://127.0.0.1:8501
    export export CONSUL_HTTP_TOKEN='${cluster_master_token}'
- owner: root:root
  path: /etc/consul/default_policies/set_default_policies.sh
  permissions: '0755'
  content: |
    #!/bin/bash
    source /etc/consul/client.env
    /usr/bin/consul acl policy create -name default-read -rules @/etc/consul/default_policies/default-policy.hcl
    /usr/bin/consul acl policy create -name node-service-write -rules @/etc/consul/default_policies/node-service-write.hcl
    /usr/bin/consul acl token update -id 00000000-0000-0000-0000-000000000002 -policy-name default-read
    /usr/bin/consul acl token create -accessor='${client_token}' -secret='${client_token}' -policy-name='node-service-write'
runcmd:
  - [ systemctl, daemon-reload ]
  - [ systemctl, enable, consul.service ]
  - [ systemctl, start, --no-block, consul.service ]
  - [ /usr/bin/bash, /etc/consul/default_policies/set_default_policies.sh ]
power_state:
  mode: reboot
  condition: True